// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package owncloud

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "owncloud", asset.ModuleFieldsPri, AssetOwncloud); err != nil {
		panic(err)
	}
}

// AssetOwncloud returns asset data.
// This is the base64 encoded gzipped contents of module/owncloud.
func AssetOwncloud() string {
	return "eJy8Vd1q4zwQvfdTHPphctP6AQJfoezNFnbZsvRuKWViTRxRWVIluanffpF/gh0ndbokDQTHkzMzR6Ojoxu8cL2E2epcmUokQJBB8RJXfegqAQT73EkbpNFL3CYAdhn4aUSlOEmA/+IXjxuGr70yBdbGlRSQk8aKkW9IFywQDByX5o1hHEgISN0CpdFZU+Jex7iMgYgOG0bq2CrKuWQdfIoVK7NFqviNVdo3qDyLa6yqABkgffPe1CMPgmAhcwosYMlRyYFdX7yjq0xRSF1gTblUMtQgXW+pznZLWyhTZC04aykv8P8tFn9Sx6/3In2KP0oT+E4IF98qz82TrI2PksPGNLDKqfQJacneU8Hp4joB1pKV8MtmujfQVPJoX+In1JaXKJypbBc5sDPjSsNqjl8r9uFZit1fexV+twhIwTrItWSXHKgSl/hMQjj2flCpZUdK0jBqKWyW8KZyOWfTpL32sTTuH9ABYdbNDnXMB3mlLBy1WcFVPKUZZ38iuQjNYtYxXr+2+lsj9oiMwJ5XlAxHBe+3m6VH1h7rdmetilKN8s+NDvwepvmtlk5c4CYEm3UzzCaZo+bfHx8f+nFPm8xP3alTh+5UZpwspCY1J8eY8RkW3bk6kckUPSLxwxQHIPscJhSMHnEelXxQTJ4b8xvEB2h+p9JGGx4gu9ikk6D6S/oEefyAnLXRivIX1kcVepZevSJeuN4aJ/7BKs+65Blf/JIlf2SAZyXQGNpkAsf98PLNp9fL5QgMb28cuKw/sPjP0jqV2Jwy5mz6rEdhxo0vLwZ5WSHubNuUJPWXnvi/AQAA//+iwH/m"
}
